peerDependencyRules:
  # Suppress warnings about these peer dependencies which we don’t need.
  ignoreMissing:
    - '@types/react'
    - 'react'
    - 'react-dom'
    - 'vite'

# We don’t need to run these build scripts, so explicitly disallow them as a minor security measure.
allowBuilds:
  esbuild: false
  sharp: false
